image: gitpod/workspace-full

tasks:
  - init: sdkmanager \"platform-tools\" \"platforms;android-33\" \"build-tools;33.0.0\"
    command: ./gradlew build

ports:
  - port: 8601
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - kotlinlang.kotlin
    - redhat.java
