image: gitpod/workspace-full

tasks:
  - init: sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
    command: ./gradlew build

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - kotlinlang.kotlin
    - redhat.java
